simulation:
  name: "Two-Body Test Barnes Hut"
  engine: "barnes_hut"
  dt: 0.0005
  t_total: 12.5663706144
  output_dir: "results_test"
  G: 1.0

bodies:
  list:
    - id: "BodyA"
      mass: 1.0
      radius: 0.1
      position: [1.0, 0.0]   # orbiting center of mass at x=-r/2
      velocity: [0.0, 0.5]  # perpendicular velocity for circular orbit
    - id: "BodyB"
      mass: 1.0
      radius: 0.1
      position: [-1.0, 0.0]    # x=r/2
      velocity: [0.0, -0.5]

preprocess:
  normalize_positions: false
  normalize_velocities: false
